/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // NVIDIA Material Design 3 dark theme
        'nv-primary': '#94da32',
        'nv-primary-dim': '#aff74e',
        'nv-primary-fixed': '#aff74e',
        'nv-primary-fixed-dim': '#94da32',
        'nv-primary-container': '#76b900',
        'nv-on-primary': '#203700',
        'nv-on-primary-container': '#284400',
        'nv-on-primary-fixed': '#102000',
        'nv-on-primary-fixed-variant': '#304f00',
        'nv-inverse-primary': '#416900',
        'nv-secondary': '#c6c6c6',
        'nv-secondary-fixed': '#e2e2e2',
        'nv-secondary-fixed-dim': '#c6c6c6',
        'nv-secondary-container': '#474747',
        'nv-on-secondary': '#303030',
        'nv-on-secondary-fixed': '#1b1b1b',
        'nv-on-secondary-fixed-variant': '#474747',
        'nv-on-secondary-container': '#b5b5b5',
        'nv-tertiary': '#c8c6c5',
        'nv-tertiary-fixed': '#e5e2e1',
        'nv-tertiary-fixed-dim': '#c8c6c5',
        'nv-tertiary-container': '#a8a6a6',
        'nv-on-tertiary': '#313030',
        'nv-on-tertiary-fixed': '#1c1b1b',
        'nv-on-tertiary-fixed-variant': '#474746',
        'nv-on-tertiary-container': '#3c3c3c',
        'nv-error': '#ffb4ab',
        'nv-error-container': '#93000a',
        'nv-on-error': '#690005',
        'nv-on-error-container': '#ffdad6',
        'nv-surface': '#121414',
        'nv-surface-dim': '#121414',
        'nv-surface-bright': '#383939',
        'nv-surface-variant': '#343535',
        'nv-surface-container-lowest': '#0d0e0f',
        'nv-surface-container-low': '#1b1c1c',
        'nv-surface-container': '#1f2020',
        'nv-surface-container-high': '#292a2a',
        'nv-surface-container-highest': '#343535',
        'nv-on-surface': '#e3e2e2',
        'nv-on-surface-variant': '#c1cab1',
        'nv-inverse-surface': '#e3e2e2',
        'nv-inverse-on-surface': '#303031',
        'nv-background': '#121414',
        'nv-on-background': '#e3e2e2',
        'nv-outline': '#8c947d',
        'nv-outline-variant': '#424936',
        'nv-surface-tint': '#94da32',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        unit: '4px',
        'margin-mobile': '16px',
        gutter: '24px',
        'container-max': '1440px',
        'margin-desktop': '48px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Hanken Grotesk', 'system-ui', 'sans-serif'],
        label: ['Geist', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '1.0', letterSpacing: '0.08em', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
